### ISSUE TITLE
'streamGenerateContent' generates a '403' error on Public  Gemini API

### ISSUE THREAD

**Issue by avastmick** [avastmick/google-generative-ai-rs#12]
**Describe the bug**
The public Gemini API supports streamed API responses. See: [Stream Generate Content in API docs](https://ai.google.dev/tutorials/rest_quickstart#stream_generate_content).

When using a 'streamGenerateContent' generates a '403' error on Public  Gemini API.

```bash
Error: GoogleAPIError { message: "HTTP Error: 403: Forbidden", code: Some(403) }
```

**To Reproduce**
In `examples/test_request.rs`

```rust
    // Either run as a standard text request or a stream generate content request
    // let client = Client::new(env::var("API_KEY").unwrap().to_string());

    // UNCOMMENT THIS SECTION
    let client = Client::new_from_model_reponse_type(
        google_generative_ai_rs::v1::gemini::Model::GeminiPro,
        env::var("API_KEY").unwrap().to_string(),
        google_generative_ai_rs::v1::gemini::ResponseType::StreamGenerateContent,
    );
```

```bash
API_KEY=[YOUR_API_KEY] RUST_LOG=info cargo run --package google-generative-ai-rs  --example text_request
Compiling google-generative-ai-rs v0.1.5 (/Users/[USER_NAME]/repos/google-generative-ai-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.91s
     Running `target/debug/examples/text_request`
Error: GoogleAPIError { message: "HTTP Error: 403: Forbidden", code: Some(403) }
```

**Expected behavior**
It should support 'streamGenerateContent' as expected, as per the Vertex AI endpoint and as per `cURL`

**Version (please complete the following information):**
 - Version 0.1.5

**Additional context**
Using `cURL` works fine for the Public API endpoint.

```bash
curl https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent?key=${API_KEY} \
        -H 'Content-Type: application/json' \
        --no-buffer \
        -d '{ "contents":[{"parts":[{"text": "Write long a story about a magic backpack."}]}]}' 
```

**Comment by hitsmaxft** [comment]
invoking google auth manager is not necessary if key exists.

**Comment by avastmick** [comment]
@hitsmaxft You are correct sir! Thank you - I wasn't thinking. I do not use the public API, only the Vertex endpoint, so I didn't think of it! 🤪
