### ISSUE TITLE
stream output miss first text

### ISSUE THREAD

**Issue by xmlandroid** [avastmick/google-generative-ai-rs#36]
use the code:
                    GeminiClient::for_each_async(json_stream, move |response: GeminiResponse| async move {
                        println!(
                            "{}",
                            response.candidates[0].content.parts[0]
                                .text
                                .clone()
                                .unwrap()
                                .as_str()
                        );
                    })
output  miss first text:

![P60`7 }F73I$N)NO__3{KU8](https://github.com/avastmick/google-generative-ai-rs/assets/15960308/b528a044-c601-4fb8-abdb-e4480dbc4f67)

this is the aistudio output:

![K1E32A_ 0}4MZ_N_{`Y8SWW](https://github.com/avastmick/google-generative-ai-rs/assets/15960308/9bd2d122-4f37-4985-ab31-6f1590b74c7e)

try a lot of example ,the problem continue

**Comment by avastmick** [comment]
Thanks, I'll investigate when I get time over the weekend.

**Comment by avastmick** [comment]
Hi, @xmlandroid, I cannot replicate this in any way. I always see all of the response from the API.

So I can help you further, can you give more techical details on your usage? Please include:

- version of crate
- whether the 'beta' features are enabled
- whether this is using the open API or using Vertex
- A more comprehensive listing of the code you are using to fetch/process the response.

**Comment by xmlandroid** [comment]
I find the problem is when I use serde_json::from_string convert the Value to GeminiResponse the first chunk will return Err not Ok

**Comment by xmlandroid** [comment]
other  chunk is ok，just the first Gemini return  struct is different ,convert the value to GeminiResponse get Err

**Comment by xmlandroid** [comment]
![1717162098155](https://github.com/avastmick/google-generative-ai-rs/assets/15960308/09fd722b-f1f1-4c12-b528-6767d37fc59d)

**Comment by xmlandroid** [comment]
![1717162214055](https://github.com/avastmick/google-generative-ai-rs/assets/15960308/e40f762f-155e-4b87-9a6b-de8ca087c44c)

**Comment by xmlandroid** [comment]
By the way, do you have any examples of conversations with pictures?
